### ISSUE TITLE
Extensions cleanup build issue

### ISSUE THREAD

**Issue by jamiehush** [rapid7/mettle#107]
It looks like a line in `mettle/configure.ac` was missed during the recent extensions cleanup. Believe we need to remove the reference to `extensions/common/Makefile`. 

Additionally, believe there's a spare comma at the end of the line starting `AC_SUBST([PLATFORM_LDADD], ...]),` in that file too.

**Comment by timwr** [comment]
Oops you might be right, can you send us a pull request?

**Comment by timwr** [comment]
I just send a pull request. Thanks for reporting.
How did you reproduce it?
Which OS are you building on and which target?
I can reproduce with `make TARGET=aarch64-iphone-darwin` on OSX (but I have other changes)

**Comment by jamiehush** [comment]
I'm building using a container based on the repo Dockerfile (under Fedora 27). Definitely reproduced on default x86_64 but looked like it affected many of the builds when using `make-all`.
