### ISSUE TITLE
RFC: CJAG transport

### ISSUE THREAD

**Issue by sempervictus** [rapid7/mettle#112]
In the event that cache-jamming agreements still work with KPTI doing all that flushing for every IRQ and CSW due to some massive screw up in speculative execution context checks, we should look into [CJAG](https://github.com/IAIK/CJAG) transports as a form of session or pivot-only-sessions (like named pipes are for now). Like dragging a magnet from the other side of the door to open the latch, sure to piss of sysadmins and defenders up and down the ecosystem :).
ping @acammack-r7: something tells me you might have thoughts on this.

**Comment by bwatters-r7** [comment]
This is fascinating, but not feasible.
