### ISSUE TITLE
Uploading File Crashes osx meterpreter

### ISSUE THREAD

**Issue by bwatters-r7** [rapid7/mettle#129]
When you upload a file with either staged or stageless reverse_tcp, mettle crashes:
## Framework Window:
```
[*] Started reverse TCP handler on 192.168.135.111:4567 
[*] Transmitting first stager...(210 bytes)
[*] Transmitting second stager...(4088 bytes)
[*] Sending stage (802816 bytes) to 192.168.134.105

meterpreter > sysinfo
Computer     : msfusers-Mac.local
OS           :  (MacOSX 17.0.0)
Architecture : x64
BuildTuple   : 
Meterpreter  : x64/osx
meterpreter > upload README.md
[*] uploading  : README.md -> README.md

[*] 192.168.134.105 - Meterpreter session 10 closed.  Reason: Died
[-] Error running command upload: Rex::TimeoutError Operation timed out.

```
## Mettle Debug Window:
![image](https://user-images.githubusercontent.com/17987018/40861714-adecbfce-65af-11e8-9b5f-1de23a8c5893.png)

**Comment by timwr** [comment]
I think this is not quite right: https://github.com/rapid7/mettle/blob/master/mettle/src/channel.c#L430
for me `cbs->tell_cb` is NULL so it crashes here: https://github.com/rapid7/mettle/blob/master/mettle/src/channel.c#L433
I can fix the crash by returning p, but then I get:
```
[*] Uploaded -1.00 B of 2.48 KiB (-0.04%): README.md -> README.md
[*] uploaded   : README.md -> README.md
```
The upload does successfully complete though.
