### ISSUE TITLE
Build fails on Ubuntu Bionic for x86_64-w64-mingw32

### ISSUE THREAD

**Issue by DoktorCranium** [rapid7/mettle#181]
All other  platform triples build fine only (i686-w64-mingw32 builds ok) 

user@linux ~/metasploit-framework/external/mettle $ make TARGET=x86_64-w64-mingw32
Building mettle for x86_64-w64-mingw32
In file included from /home/user/metasploit-framework/external/mettle/mettle/src/stdapi/fs/file.c:24:0,
                 from /home/user/metasploit-framework/external/mettle/mettle/src/stdapi/stdapi.c:8:
/home/user/metasploit-framework/external/mettle/mettle/src/stdapi/sys/process.c: In function ‘sys_process_read’:
/home/user/metasploit-framework/external/mettle/mettle/src/stdapi/sys/process.c:186:13: error: format ‘%u’ expects argument of type ‘unsigned int’, but argument 4 has type ‘ssize_t {aka long long int}’ [-Werror=format=]
   log_debug("read %" PRIuS " bytes for channel", rc);
             ^
/home/user/metasploit-framework/external/mettle/mettle/src/log.h:65:44: note: in definition of macro ‘log_debug’
  if (_zlog_level >= 1) zlog_time(ZLOG_LOC, format "\n", ##__VA_ARGS__)
                                            ^~~~~~
In file included from /home/user/metasploit-framework/external/mettle/mettle/src/printf_format.h:14:0,
                 from /home/user/metasploit-framework/external/mettle/mettle/src/tlv.h:19,
                 from /home/user/metasploit-framework/external/mettle/mettle/src/channel.h:13,
                 from /home/user/metasploit-framework/external/mettle/mettle/src/mettle.h:11,
                 from /home/user/metasploit-framework/external/mettle/mettle/src/stdapi/stdapi.c:7:
/home/user/metasploit-framework/external/mettle/mettle/include/compat/stdio.h:22:17: note: format string is defined here
 #define PRIuS "Iu"
cc1: all warnings being treated as errors
make[2]: *** [stdapi/stdapi.lo] Error 1
make[1]: *** [install-recursive] Error 1
make/Makefile.mettle:67: recipe for target '/home/user/metasploit-framework/external/mettle/build/x86_64-w64-mingw32/bin/mettle.built' failed
make: *** [/home/user/metasploit-framework/external/mettle/build/x86_64-w64-mingw32/bin/mettle.built] Error 2
user@linux ~/metasploit-framework/external/mettle $

**Comment by busterb** [comment]
The build is now fixed in #186 , thanks.
