### ISSUE TITLE
Sessions respawn endlessly from linux/armle/mettle/reverse_tcp

### ISSUE THREAD

**Issue by jduck** [rapid7/mettle#24]
This was an issue we had during development (before mettle landed on master). I thought we fixed it on the dev branches and thus thought the fix would make it to master too. It seems not.

When I kill msfconsole entirely ("quit -y" from msf prompt with existing session) and restart it I get a session immediately.

If I exit the session intentionally ("quit" command from meterpreter) it does not happen.

When this session appears it does not load stdapi on msf side and thus the resulting session is not usable.

**Comment by jduck** [comment]
One more thing... Once the device gets in this state even quitting the session doesn't work. It seems something is timing out in negotation and the session eventually dies/respawns.

**Comment by jduck** [comment]
Well... Now I still get a session in perpetude but at least it's a usable one =) Also I can still quit it intentionally to stop the repeated sessions. I'm guessing this is a resiliency feature kicking in. Are there any variables to control that?

**Comment by busterb** [comment]
Heh, I'm confused. The shutdown command does a null pointer deref to kill the session. How does it keep running? Does your environment catch sigsegv and continue chugging along?

**Comment by jduck** [comment]
I thought we switched to exit() or similar along the way? I'm definitely not seeing a crash in tombstones. Maybe if mettle is resetting signal handlers to default that won't happen tho.

I suspect the big difference is between "quit -y" in msf (without ever having attaching to the session) and attaching/exiting the session.

**Comment by busterb** [comment]
oh, are you actually exiting the session? I don't think quit -y will actually tell the sessions to shut down.

**Comment by OJ** [comment]
Correct, it doesn't. Since resilient transports appeared, the TCP
transports behave like HTTP transports when it comes to quitting. It has to
be done directly on the session.
