### ISSUE TITLE
Mettle is only sending 15b of UUID - failure to launch

### ISSUE THREAD

**Issue by sempervictus** [rapid7/mettle#47]
Mettle seems to have broken the UUID exchange with framework, resulting in log messages similar to:
```
[12/12/2016 02:33:44] [d(0)] core: Session 36 did not respond to validation request ArgumentError: Raw UUID must be at least 16 bytes, got ӝ����������� 15
```
with the comma and after added for debugging purposes on this side.

If i had to guess, i'd say by the commit in 55f43d, that there's some strange behavior going on with b64 encoding, and given the recent reversion of another b64 commit, i'm guessing we're attempting to encode/decode something we shouldnt.

Ping @bcook-r7 and @OJ for the UUID nightmare he unleashed on us all ;-)

This happens in our barely diverged branch and master.

**Comment by busterb** [comment]
Make sure your branch is pointing to metasploit_payloads-mettle 0.1.4. That changed the API a little from expecting a UUID object to a string.

**Comment by sempervictus** [comment]
Looks like reverting 2d0479d32976d3372e183ef4efee5e69894d14be fixes it though...

**Comment by sempervictus** [comment]
Branch...? My gem version is 0.1.5, local branch names follow the version file in this repo. The Gemfile for MSF points to local repositories for the stuff i tinker with...

I'm running framework with last R7 commit cfca18906, payloads at master, and mettle with your network channels PR. Any chance the migration stubs PR for MSF is breaking my end of it?

**Comment by busterb** [comment]
This needs https://github.com/rapid7/metasploit-framework/pull/7681 or it will cause problems.

**Comment by sempervictus** [comment]
Thank you sir, with the latest master + mettle stageless PR it seems to work....
Separately, portfwds no longer cause crashes. still dont work, but at least dont kill the session (with your latest PR)
