### ISSUE TITLE
Staged Mettle payloads currently unstable

### ISSUE THREAD

**Issue by sempervictus** [rapid7/mettle#61]
Mettle builds and connects back via staged payloads from non PAX MPROTECT enabled hosts, stageless payloads connect back from either.
When loading a staged payload (linux/x86/mettle/reverse_tcp), instability is almost immediate - stdapi _usually_ loads, and the first command will run (sysinfo, ps, etc), second command triggers a timeout, usually killing the session. Stageless payloads do not exhibit this behavior, indicating possible socket/transport issues in the stage setup.
Something went south in the stage code recently, possibly having to do with the HTTP work. Ping @bcook-r7 & @timwr: are you folks seeing the same thing off of current master?

**Comment by busterb** [comment]
Thanks @sempervictus - I've been doing a bunch of surgery on that area of code lately, and will verify that things look ok before the next gem release. Since mettle has stdapi built-in (there's nothing to load), it makes me think it's a general transport issue.

**Comment by sempervictus** [comment]
Thanks boss, iirc we saw something like this before - where stages broke, stageless worked, about two months ago. Maybe the fix from back then is breaking stuff now?

**Comment by timwr** [comment]
@sempervictus I'm not seeing the same thing with `linux/armle/mettle/reverse_tcp`

**Comment by busterb** [comment]
HEAD is working in staged mode for me after the big transport conversion. I'll reopen if you're still seeing issues.
