### ISSUE TITLE
UAF on channel closing with cmd_exec

### ISSUE THREAD

**Issue by timwr** [rapid7/mettle#64]
When a process closes the channel is sometimes freed before the exit_cb is invoked.
This means the channel manager can be overwritten, resulting in a crash here:
https://github.com/rapid7/mettle/blob/master/mettle/src/channel.c#L131
with the callstack:
https://github.com/rapid7/mettle/blob/master/mettle/src/channel.c#L191
https://github.com/rapid7/mettle/blob/master/mettle/src/stdapi/sys/process.c#L206
https://github.com/rapid7/mettle/blob/master/mettle/src/process.c#L215
This easiest way to reproduce this is to run `cmd_exec("sleep 1;echo test;sleep 1")` on a mettle session (perhaps multiple times).
If the fix isn't obvious (it's not to me) then I can have a go at fixing it, perhaps by keeping track of the channels/channelmgr another way.
Side note: `cmd_exec("echo test")` sometimes doesn't return "test" too.

**Comment by busterb** [comment]
Hmm, my first thought was to store a direct reference to the channel in the process callback, then tombstone one side or the other so we don't end up with AB / BA problems and can free in a consistent order.

**Comment by busterb** [comment]
Hmm, channel_shutdown seems like what we want for setting a tombstone flag, if we could replace the channel_send_close_request in exit_cb with that... doesn't work just yet, digging into why.
