### ISSUE TITLE
execute from memory on x64 linux

### ISSUE THREAD

**Issue by gelim** [rapid7/mettle#81]
Hi,
I'm looking for 'execute -m' on a x64 linux mettle target but it appears it is not implemented. In https://github.com/rapid7/mettle/blob/master/mettle/src/stdapi/sys/process.c#L235 there is no handling of potential (doesn't exist in `mettle/src/tlv_types.h`) flag `PROCESS_EXECUTE_FLAG_MEMORY`.  Can you confirm that I'm not missing something obvious, and is this feature in a roadmap somewhere?

In the meantime is there an alternative way to realize that without modifying too much mettle, by showing off bootstraping in mettle an ELF (like a new thread, or a new process) locally stored on the control side.

Cheers,

**Comment by sempervictus** [comment]
POSIX doesn't do the whole createremotethread bit, the memory model is rather well separated. This would probably be achieved via an ldpreload or some other process hollowing/infection via ptrace or ftrace sort of thing. 

@acammack-r7: is libhijack an option here? Sorta figured we would need it for migration anyway.

**Comment by acammack-r7** [comment]
What is the goal of using `-m` on Linux? If you just want a different process name to show up, we can set `ARGV[0]` to whatever we want when we exec, and that wouldn't be too hard to add. If we want to avoid a particularly suspicious entry in `/proc/self/maps` then we will need something like libhijack, but it would need a bit of work to suit our purposes, I think.

**Comment by sempervictus** [comment]
On my end - avoid disk writes via process hollowing or similar in memory method. I don't want my payload going on disk and into an FS snapshot for later reversing.

**Comment by acammack-r7** [comment]
I see. An intermediate step could be to achieve that could make a simple stager program that loads and runs an ELF (similar to the mettle stagers) that is passed in over stdin. That way the payload itself doesn't hit the FS. The program passed in would need to be compiled like mettle, which is probably desirable anyway because who knows what's in the system libs.

**Comment by sempervictus** [comment]
Can we use the extension system to load a dummy ext memory space and execute in that, from memory?

**Comment by busterb** [comment]
This is now implemented as part of #154
