### ISSUE TITLE
TlvCrypt

### ISSUE THREAD

**Issue by sempervictus** [rapid7/mettle#95]
What's the state of l7 crypto at this point? Last I'd checked were compatible in our tlv format and init semantics here, but don't actually have crypto running.

**Comment by jmartin-r7** [comment]
Added for non-windows platforms in #136

**Comment by bwatters-r7** [comment]
Since this is supported for non-windows, should we close this?  I can't see windows support coming super-fast on this.

**Comment by sempervictus** [comment]
Windows has tlvcrypt, and mettle can build for windows. Closing, already built the bins but haven't tested yet. Thanks a ton.
